# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-01 07:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_choice_voters'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='voters',
        ),
        migrations.RemoveField(
            model_name='question',
            name='question_discription',
        ),
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(),
        ),
    ]
